@startuml
!include diagrams/tree/tree.puml
!include diagrams/tree/split/split.puml
!include diagrams/tree/loss_fn/loss_fn.puml

package "src/ensembles" as ENSEMBLES{
  package "gb" as GB {
    class GradientBoosting {
      +trees : Vec<Tree>
      +alpha : f64
      +fit(samples: DataSet, target: Target<T>, tree_config: TreeConfig, score_fn: Score<T>) : Result<Tree, TreeError>
    }

    GradientBoosting *-- Tree : trees
  }
}

GB --[hidden]> Tree
Tree --[hidden]> SPLIT
SPLIT --[hidden]> LOSS_FN

@enduml
